apiVersion: v1
kind: Pod
metadata:
  name: network-debug
  namespace: tfe
  labels:
    app: network-debug
    purpose: troubleshooting
spec:
  containers:
  - name: network-tools
    image: nicolaka/netshoot:latest
    command:
      - tail
      - -f
      - /dev/null
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      capabilities:
        add:
          - NET_ADMIN
          - NET_RAW
    env:
    - name: TERM
      value: "xterm"
  restartPolicy: Never
